
Working on fortran code
[[./FsiStuff.f90]]

Increase the speed


* compile fortran function

#+begin_src shell :results raw drawer
cd /home/me/CAE/FluidStructureBeam
elmerf90 FsiStuff.f90  -o FsiStuff.so
#+end_src

#+RESULTS:
:results:
no elmerice
/usr/bin/f95 FsiStuff.f90 -o FsiStuff.so -fopenmp -DCONTIG= -DHAVE_EXECUTECOMMANDLINE -DUSE_ISO_C_BINDINGS -DUSE_ARPACK -O2 -g -DNDEBUG -fPIC -shared -I/usr/local/share/elmersolver/include -L/usr/local/share/elmersolver/../../lib/elmersolver -shared -lelmersolver 
:end:




FUNCTION InFlow( Model, n, x ) RESULT( vin )
Model: My model
Node: the node
x: the vartiable ( here is time)



#+RESULTS:
:results:
no elmerice
/usr/bin/f95 FsiStuff.f90 -o FsiStuff.so -fopenmp -DCONTIG= -DHAVE_EXECUTECOMMANDLINE -DUSE_ISO_C_BINDINGS -DUSE_ARPACK -O2 -g -DNDEBUG -fPIC -shared -I/usr/local/share/elmersolver/include -L/usr/local/share/elmersolver/../../lib/elmersolver -shared -lelmersolver 
:end:



* execute grid
#+begin_src shell :results raw drawer
cd /home/me/CAE/FluidStructureBeam
ElmerGrid 1 2 fsi.grd
#+end_src

#+RESULTS:
:results:

Starting program Elmergrid
Elmergrid reading in-line arguments
Output will be saved to file fsi.

Elmergrid loading data:
-----------------------
Loading the geometry from file 'fsi.grd'.
Loading ElmerGrid file version: 210903
Defining the coordinate system (2-DIM).
Loading 8 subcell limits in X-direction
Loading 7 subcell limits in Y-direction
Loading material structure
LoadElmergrid: materials interval is [1,6]
Loading boundary conditions
Found 6 boundaries
Loading minimum number of elements
Reached the end of command file
Found 1 divisions for grid

Loading ElmerGrid commands from file 'fsi.grd'.
Reached the end of command file
Read commands from a file

Elmergrid creating and manipulating meshes:
-------------------------------------------
20 cells were created.
Numbered 40535 knots in 10020 9-node elements.
Numbering order was <y><x> and max levelwidth 244.
60 element sides between materials 6 and 1 were located to type 1.
60 element sides between materials 4 and 1 were located to type 2.
120 element sides between materials 2 and 1 were located to type 3.
165 element sides between materials 3 and 1 were located to type 4.
165 element sides between materials 5 and 1 were located to type 5.
2 element sides between materials 5 and 2 were located to type 6.
Coordinates defined in 2 dimensions

Elmergrid saving data with method 2:
-------------------------------------
Saving mesh in ElmerSolver format to directory fsi.
Reusing an existing directory
Saving 40535 coordinates to mesh.nodes.
Saving 10020 element topologies to mesh.elements.
Saving boundary elements to mesh.boundary.
Saving header info to mesh.header.

Thank you for using Elmergrid!
Send bug reports and feature wishes to elmeradm@csc.fi
:end:



* run it


#+begin_src sh :async :results raw drawer
cd /home/me/CAE/FluidStructureBeam

#+end_src

